### ISSUE TITLE
FadeEvent fails

### ISSUE THREAD

**Issue by JFixby** [RedTriplane/RedTriplane#19]
```
 public void startGame() {
	GameUI.pushFadeOut(0); <<<<<<<<<<<<<<
	GameUI.showLoadingScreen(loader_ui_unit_id);
	GameUI.pushFadeIn(fade_time);
```

```
Current unit is null. Task failed FadeEvent [FADE_OUT] period=0
java.lang.NullPointerException
java.lang.NullPointerException
	at com.jfixby.r3.ui.FadeEvent.go(FadeEvent.java:48)
	at com.jfixby.r3.ui.TintoUIEventsQueue$1.doDo(TintoUIEventsQueue.java:35)
	at com.jfixby.red.sys.RedTask.push(RedTask.java:78)
	at com.jfixby.red.sys.RedTaskManager.push(RedTaskManager.java:81)
	at com.jfixby.red.sys.RedSystemExecutor.pushTasks(RedSystemExecutor.java:34)
	at com.jfixby.cmns.api.taskman.SysExecutor.pushTasks(SysExecutor.java:28)
	at com.jfixby.redtriplane.fokker.adaptor.GdxAdaptor.do_full_cycle(GdxAdaptor.java:94)
	at com.jfixby.redtriplane.fokker.adaptor.GdxAdaptor.render(GdxAdaptor.java:51)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:223)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:124)
```

**Comment by JFixby** [comment]
not reproducible?
