### ISSUE TITLE
TTFFontCache leak 

### ISSUE THREAD

**Issue by JFixby** [RedTriplane/RedTriplane#27]
```
Exception in thread "LWJGL Application" java.lang.NullPointerException
	at java.lang.System.arraycopy(Native Method)
	at com.jfixby.red.engine.core.unit.text.VerticesCache.updateRegion(VerticesCache.java:22)
	at com.jfixby.red.engine.core.unit.text.RedRasterizedString.getVertices(RedRasterizedString.java:360)
	at com.jfixby.redtriplane.fokker.render.raster.SpritesRenderer.drawString(SpritesRenderer.java:250)
	at com.jfixby.redtriplane.fokker.render.raster.FokkerRasterRenderer.drawString(FokkerRasterRenderer.java:114)
	at com.jfixby.redtriplane.fokker.render.FokkerRenderMachine.drawString(FokkerRenderMachine.java:250)
	at com.jfixby.red.engine.core.unit.text.RedRasterizedString.doDraw(RedRasterizedString.java:192)
	at com.jfixby.red.engine.core.unit.RedLayerRenderer.renderComponent(RedLayerRenderer.java:152)
	at com.jfixby.red.engine.core.unit.RedLayerRenderer.renderLayer(RedLayerRenderer.java:98)
	at com.jfixby.red.engine.core.unit.RedLayerRenderer.renderLayer(RedLayerRenderer.java:96)
	at com.jfixby.red.engine.core.unit.RedLayerRenderer.renderLayer(RedLayerRenderer.java:96)
	at com.jfixby.red.engine.core.unit.RedLayerRenderer.renderLayer(RedLayerRenderer.java:96)
	at com.jfixby.red.engine.core.unit.RedLayerRenderer.renderLayer(RedLayerRenderer.java:96)
	at com.jfixby.red.engine.core.unit.RedLayerRenderer.renderAll(RedLayerRenderer.java:49)
	at com.jfixby.red.engine.core.unit.RedUnitExecutor.render(RedUnitExecutor.java:74)
	at com.jfixby.red.engine.core.unit.RedUnitExecutor.render(RedUnitExecutor.java:103)
	at com.jfixby.red.engine.core.unit.UnitContainer.doRender(UnitContainer.java:81)
	at com.jfixby.red.engine.core.UnitsManager.render(UnitsManager.java:42)
	at com.jfixby.red.engine.core.RedUnitsMachine.doRender(RedUnitsMachine.java:134)
	at com.jfixby.redtriplane.fokker.adaptor.GdxAdaptor.do_full_cycle(GdxAdaptor.java:102)
	at com.jfixby.redtriplane.fokker.adaptor.GdxAdaptor.render(GdxAdaptor.java:52)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
```

**Comment by JFixby** [comment]
```
public class VerticesCache {
	float[][] spriteVertices;
	int[] sprites;

	public void updateNumberOfRegions (final int n) {
		this.spriteVertices = new float[n][];
		this.sprites = new int[n];
	}

	public void updateRegion (final int region, final float[] spriteVertices) {
		if (this.spriteVertices[region] == null || this.spriteVertices[region].length < spriteVertices.length) {
			this.spriteVertices[region] = new float[spriteVertices.length];
			this.sprites[region] = spriteVertices.length / SpritesRenderer.SPRITE_SIZE;
			L.d("LEAK");
		}
		System.arraycopy(spriteVertices, 0, this.spriteVertices[region], 0, spriteVertices.length);

	}

	public int getNumberOfSprites (final int region) {
		return this.sprites[region];
	}

	public float[] getVertices (final int region) {
		return this.spriteVertices[region];
	}

}
```

**Comment by JFixby** [comment]
Should remove VerticesCache
